### ISSUE TITLE
CryptographyDeprecationWarning with a seemingly simple fix

### ISSUE THREAD

**Issue by vahp** [web-push-libs/vapid#105]
getting this straightforward-looking warning when running vapid

> $ vapid --gen
/Users/me/myproject/venv/lib/python3.11/site-packages/py_vapid/__init__.py:200: CryptographyDeprecationWarning: Curve argument must be an instance of an EllipticCurve class. Did you pass a class by mistake? This will be an exception in a future version of cryptography.
  self.private_key = ec.generate_private_key(ec.SECP256R1, default_backend())

it seems to me that you can fix it with with a pair of parens  : ec.SECP256R1()
I'm leery of messing with other people's security code so just opening this as an issue.

**Comment by jrconlin** [comment]
Sigh. 

The fun of dependent library changes...

**Comment by daviddanielng** [comment]
2024 warning is now 2025 error.

```shell


david@codespace:~$ vapid
No private key file found.
Do you want me to create one for you? (Y/n)y
Traceback (most recent call last):
  File "/home/david/.local/bin/vapid", line 7, in <module>
    sys.exit(main())
             ^^^^^^
  File "/home/david/.local/pipx/venvs/py-vapid/lib/python3.11/site-packages/py_vapid/main.py", line 60, in main
    vapid.generate_keys()
  File "/home/david/.local/pipx/venvs/py-vapid/lib/python3.11/site-packages/py_vapid/__init__.py", line 200, in generate_keys
    self.private_key = ec.generate_private_key(ec.SECP256R1,
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: curve must be an EllipticCurve instance
david@codespace:~$ 

```

**Comment by jrconlin** [comment]
Screw it, made a [PR](https://github.com/web-push-libs/vapid/pull/110)

Since it's thursday, I probably won't merge this 'til Monday, since I'll be potentially traveling then.

**Comment by gauravmm** [comment]
Thanks for figuring this out!
